spring:
  datasource:
    username: jeju
    password: jeju
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/jejunu

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
